def stop_words():
    stopwords = [
        "ó", "né", 'aí', "isso", ".... ", "..", "...", "|", "?", "!", "vc""né", "gente",
        "então", "tá", "ai", "só", ",", "eh", ".", 'a', 'abaixo', 'acerca', 'acima', 'ademais', 'adeus', 'agora',
        'ainda',
        'algo', 'algumas', 'alguns', 'ali', 'ambos', 'antes', 'ao', 'aos', 'aonde',
        'apenas', 'apesar', 'após', 'aquela', 'aquelas', 'aquele', 'aqueles',
        'aquilo', 'aqui', 'as', 'assim', 'até', 'através', 'atrás', 'c', 'cada',
        'catorze', 'cedo', 'cem', 'cento', 'certamente', 'certeza', 'cinco',
        'coisa', 'com', 'como', 'conosco', 'consoante', 'consta', 'contigo',
        'contudo', 'contra', 'cuja', 'cujas', 'cujo', 'cujos', 'd', 'da', 'daquela',
        'daquelas', 'daquele', 'daqueles', 'das', 'de', 'debaixo', 'demais',
        'demasiado', 'dentro', 'depois', 'desde', 'dessa', 'dessas', 'desse',
        'desses', 'desta', 'destas', 'deste', 'destes', 'deve', 'devem', 'devendo',
        'dever', 'deverá', 'deverão', 'deveria', 'deveriam', 'devia', 'deviam',
        'dez', 'dezanove', 'dezasseis', 'dezassete', 'dezoito', 'diante', 'disso',
        'disto', 'dito', 'diz', 'dizem', 'dizer', 'do', 'dois', 'donde', 'dos',
        'doze', 'duas', 'duzentos', 'durante', 'e', 'é', 'ela', 'elas', 'ele',
        'eles', 'em', 'embora', 'enquanto', 'entre', 'era', 'eram', 'éramos',
        'és', 'essa', 'essas', 'esse', 'esses', 'esta', 'está', 'estamos',
        'estando', 'estar', 'estará', 'estaremos', 'estaria', 'estariam',
        'estaríamos', 'estava', 'estávamos', 'este', 'esteja', 'estejam',
        'estejamos', 'estes', 'esteve', 'estive', 'estivemos', 'estiver', 'estivera',
        'estiveram', 'estivéramos', 'estiverem', 'estivermos', 'estivesse',
        'estivessem', 'estivéssemos', 'estiveste', 'estivestes', 'estou', 'eu',
        'excepto', 'f', 'faço', 'falta', 'favor', 'faz', 'fazeis', 'fazem',
        'fazemos', 'fazer', 'fazes', 'feita', 'feitas', 'feito', 'feitos', 'fez',
        'fim', 'final', 'fiz', 'fizer', 'fizeram', 'fizerem', 'fizermos', 'fizesse',
        'fizéssemos', 'foi', 'fomos', 'for', 'fora', 'foram', 'fôramos', 'forem',
        'formos', 'fosse', 'fossem', 'fôssemos', 'foste', 'fostes', 'fui', 'g', 'h',
        'há', 'haja', 'hajam', 'hajamos', 'hão', 'havemos', 'havendo', 'haver',
        'haverá', 'haverão', 'haverei', 'haveremos', 'haveria', 'haveriam',
        'haveríamos', 'havia', 'haviam', 'havíamos', 'hei', 'haja', 'houve',
        'houvemos', 'houver', 'houvera', 'houveram', 'houvéramos', 'houverão',
        'houverei', 'houverem', 'houveremos', 'houveria', 'houveriam', 'houveríamos',
        'houvermos', 'houvesse', 'houvessem', 'houvéssemos', 'i', 'j', 'já',
        'jamais', 'junto', 'l', 'lá', 'lado', 'lhe', 'lhes', 'logo', 'longe',
        'm', 'maior', 'maioria', 'mais', 'mal', 'mas', 'me', 'mediante', 'meio',
        'melhor', 'menos', 'mesma', 'mesmas', 'mesmo', 'mesmos', 'meu', 'meus',
        'mil', 'minha', 'minhas', 'momento', 'muito', 'muitos', 'n', 'na', 'nada',
        'não', 'naquela', 'naquelas', 'naquele', 'naqueles', 'nas', 'nem', 'nenhum',
        'nenhuma', 'nessa', 'nessas', 'nesse', 'nesses', 'nesta', 'nestas', 'neste',
        'nestes', 'ninguém', 'no', 'noite', 'nome', 'nos', 'nós', 'nossa', 'nossas',
        'nosso', 'nossos', 'nova', 'novas', 'nove', 'novo', 'novos', 'num', 'numa',
        'nunca', 'o', 'oitava', 'oitavo', 'oito', 'onde', 'ontem', 'onze', 'os',
        'ou', 'outra', 'outras', 'outrem', 'outro', 'outros', 'p', 'para', 'parece',
        'parte', 'partir', 'pela', 'pelas', 'pelo', 'pelos', 'per', 'perante',
        'perto', 'pode', 'podem', 'podendo', 'poder', 'poderá', 'poderão', 'poderia',
        'poderiam', 'podia', 'podiam', 'põe', 'põem', 'pois', 'ponto', 'pontos',
        'por', 'porém', 'porque', 'porquê', 'portanto', 'posição', 'possível',
        'posso', 'pouca', 'poucas', 'pouco', 'poucos', 'pra', 'própria', 'próprias',
        'próprio', 'próprios', 'próxima', 'próximas', 'próximo', 'próximos', 'q',
        'quais', 'qual', 'qualquer', 'quando', 'quanta', 'quantas', 'quanto',
        'quantos', 'quão', 'que', 'quê', 'quem', 'quer', 'quereis', 'querem',
        'queremas', 'queres', 'quero', 'questão', 'quiçá', 'quinta', 'quinto', 'r',
        'relação', 's', 'sabe', 'sabem', 'são', 'se', 'seja', 'sejam', 'sejamos',
        'sem', 'sempre', 'sendo', 'ser', 'será', 'serão', 'serei', 'seremos',
        'seria', 'seriam', 'seríamos', 'sete', 'sétima', 'sétimo', 'seu', 'seus',
        'sexta', 'sexto', 'si', 'sido', 'sim', 'sob', 'sobre', 'sois', 'somos',
        'sou', 'sua', 'suas', 't', 'tão', 'tal', 'talvez', 'também', 'tampouco',
        'tanta', 'tantas', 'tanto', 'tarde', 'te', 'tem', 'têm', 'temos', 'tendo',
        'tenha', 'tenham', 'tenhamos', 'tenho', 'tens', 'ter', 'terá', 'terão',
        'terceira', 'terceiro', 'terei', 'teremos', 'teria', 'teriam', 'teríamos',
        'teu', 'teus', 'teve', 'ti', 'tido', 'tinha', 'tinham', 'tínhamos', 'tive',
        'tivemos', 'tiver', 'tivera', 'tiveram', 'tivéramos', 'tiverem', 'tivermos',
        'tivesse', 'tivessem', 'tivéssemos', 'tiveste', 'tivestes', 'toda', 'todas',
        'todavia', 'todo', 'todos', 'três', 'treze', 'tu', 'tua', 'tuas', 'tudo',
        'u', 'um', 'uma', 'umas', 'uns', 'usa', 'usar', 'v', 'vai', 'vais', 'vão',
        'várias', 'vários', 'vem', 'vêm', 'vendo', 'ver', 'vez', 'vezes', 'viagem',
        'vindo', 'vinte', 'vir', 'virá', 'virão', 'você', 'vocês', 'vos', 'vós',
        'vossa', 'vossas', 'vosso', 'vossos', 'z', 'zero', 'à', 'às', 'área'
    ]
    return stopwords